CREATE SEQUENCE IF NOT EXISTS pets_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE pets
(
    id          INTEGER NOT NULL,
    species     VARCHAR(255),
    breed       VARCHAR(255),
    name        VARCHAR(255),
    location    VARCHAR(255),
    age         VARCHAR(255),
    description VARCHAR(255),
    imgurl      VARCHAR(255),
    CONSTRAINT pk_pets PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    user_id BIGINT NOT NULL,
    role    VARCHAR(255)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_on_user_model FOREIGN KEY (user_id) REFERENCES users (id);


INSERT INTO users (username, password)
VALUES ('DariusSopom', 'password123');


INSERT INTO user_roles (user_id, role)
VALUES (1, 'admin');


INSERT INTO pets (id, species, breed, name, location, age, description, imgurl)
VALUES
    (NEXTVAL('pets_seq'), 'Dog', 'Labrador', 'Buddy', 'New York', '3', 'Friendly Labrador', 'https://example.com/buddy.jpg'),
    (NEXTVAL('pets_seq'), 'Cat', 'Siamese', 'Mittens', 'Los Angeles', '2', 'Playful Siamese cat', 'https://example.com/mittens.jpg'),
    (NEXTVAL('pets_seq'), 'Fish', 'Goldfish', 'Goldie', 'Chicago', '1', 'Small golden fish', 'https://example.com/goldie.jpg');

SELECT * FROM pets;