ALTER TABLE users
    ADD COLUMN name VARCHAR(255),
    ADD COLUMN phone VARCHAR(255) UNIQUE,
    ADD COLUMN email VARCHAR(255) UNIQUE,
    ADD COLUMN location VARCHAR(255),
    ADD COLUMN imgURL VARCHAR(255),
    ADD COLUMN bio VARCHAR(1000);
