spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.name=mydatabase
spring.datasource.username=myuser
spring.datasource.password=mypassword

# Flyway configuration
spring.flyway.enabled=true
spring.flyway.schemas=public
spring.flyway.default-schema=public

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true