spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.name=mydatabase
spring.datasource.username=myuser
spring.datasource.password=mypassword